version: '2'
services:
  moodle:
    build: .
    image: patsys/moodle
    environment:
      - MOODLE_HTDOCS=/app/www/localhost/htdocs
      - MOODLE_URL=http://moodle
      - MOODLE_LANG=de
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DB_HOST=db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=T3stT3st
      - MOODLE_SITE_FULLNAME=patsys
      - MOODLE_SITE_SHORTNAME=PATSYS
      - MOODLE_ADMIN_USER=admin
      - MOODLE_ADMIN_PASSWORD=T3stT3st!
      - MOODLE_ADMIN_EMAIL=my@noemail.com
    links:
      - db
    expose:
      - "80"
  db:
    image: patsys/mariadb
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=T3stT3st
      - MYSQL_ROOT_PASSWORD=T3stT3st
      - MYSQL_HOST=172.%.%.%
      - MYSQL_ROOT_HOST=172.%.%.%
    expose:
      - "3306"
  sut:
    image: patsys/test-webserver
    links:
      - moodle
    environment:
      - HOST=http://moodle
      - WORD=logged
      - INTERVAL=10
      - TRY=70

